Pandas- Dataframes and Series

Pandas is a powerful data manipulation library in python,widely used for data analysis and data cleaning .It provides two primary data structures :series and DataFrame. A series is a one dimensional arry like object . while a dataframes is a two dimensional , size-mutable, and potentially heterogeneous tabular data structure with labeled axes(rows and columns)

In [1]:
import pandas as pd

In [4]:
## Series

data=[1,2,3,4,5]
series=pd.Series(data)
print("Series \n",series)
print(type(series))

Series
 0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.Series'>

In [7]:
## create a Series from dictionary 

data={"a":1,"b":2,"c":3}
series_dict=pd.Series(data)
print(series_dict)

a    1
b    2
c    3
dtype: int64

In [8]:
data=[10,20,30]
index=['a','b','c']

pd.Series(data,index=index)

a    10
b    20
c    30
dtype: int64

In [9]:
## Dataframe
## create aDataframe from a dictionary of list

data={
  'name':['Ayush','rohit','Sanu'],
  'Age':[25,30,45],
  'city':['Delhi','New York','Florida']
}
df=pd.DataFrame(data)
print(df)
print(type(df))

    name  Age      city
0  Ayush   25     Delhi
1  rohit   30  New York
2   Sanu   45   Florida
<class 'pandas.DataFrame'>

In [10]:
## to read csv files we use

# df=pd.read_csv('csvfiles.csv')
# df.head(5) ## for the first 5 records
# df.tail(5) ## for the last 5 records

df

    name  Age      city
0  Ayush   25     Delhi
1  rohit   30  New York
2   Sanu   45   Florida

In [11]:
df['name']

0    Ayush
1    rohit
2     Sanu
Name: name, dtype: str

In [12]:
df.loc[0]

name    Ayush
Age        25
city    Delhi
Name: 0, dtype: object

In [17]:
df.iloc[0]

name    Ayush
Age        25
city    Delhi
Name: 0, dtype: object

In [22]:
##Accessing a specified element
int(df.at[2,'Age'])

45

In [23]:
## aceesing a specified index uning ait

df.iat[2,2]

'Florida'

In [24]:
df

    name  Age      city
0  Ayush   25     Delhi
1  rohit   30  New York
2   Sanu   45   Florida

In [ ]:
## Data manipulation with Dataframe

##Adding a column

df['Salary']=[50000,60000,70000]
df

    name  Age      city  Salary
0  Ayush   25     Delhi   50000
1  rohit   30  New York   60000
2   Sanu   45   Florida   70000

In [33]:
## Remove a column

# df=df.drop('Salary',axis=1)
## or df.drop('Salary', axis=1, inplace=True)
df

    name  Age      city
0  Ayush   25     Delhi
1  rohit   30  New York
2   Sanu   45   Florida

In [35]:
df['Age']=df['Age']+1
df

    name  Age      city
0  Ayush   27     Delhi
1  rohit   32  New York
2   Sanu   47   Florida

In [36]:
df=df.drop(0)

In [37]:
df

    name  Age      city
1  rohit   32  New York
2   Sanu   47   Florida

In [39]:
##df.describe()
df.describe(include='all')

         name        Age      city
count       2   2.000000         2
unique      2        NaN         2
top     rohit        NaN  New York
freq        1        NaN         1
mean      NaN  39.500000       NaN
std       NaN  10.606602       NaN
min       NaN  32.000000       NaN
25%       NaN  35.750000       NaN
50%       NaN  39.500000       NaN
75%       NaN  43.250000       NaN
max       NaN  47.000000       NaN